import { KeyPurpose, SignatureScheme, StackrConfig } from "@stackr/stackr-js";

// this file is generated by the deployment script
import * as deployment from "./deployment.json";



const stackrConfig: StackrConfig = {
  stackrApp: {
    appId: deployment.app_id,
    appInbox: deployment.app_inbox,
  },
  builder: {
    batchSize: 16,
    batchTime: 1000,
  },
  syncer: {
    slotTime: 1000,
    vulcanRPC: "http://vulcan.stf.xyz",
    L1RPC: "http://rpc.stf.xyz",
  },
  operator: {
    accounts: [
      {
        privateKey:
          "724aeb4d0a184e543c936f407572c0e327b234a5d26f7a83a35074c653262211",
        purpose: KeyPurpose.BATCH,
        scheme: SignatureScheme.ECDSA,
      },
    ],
  },
  domain: {
    name: "Stackr MVP v0",
    version: "1",
    chainId: 42069,
    verifyingContract: deployment.app_inbox,
    salt: "0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
  },
  datastore: {
    filePath: "./datastore",
  },
};

export { stackrConfig };
